FindYourCar/FindYourCar/Controllers/NewCarController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FindYourCar.DAO_Models;
using FindYourCar.Models;
using FindYourCar.Models.ViewModel;

namespace FindYourCar.Controllers
{
    public class NewCarController : Controller
    {
        // GET: Car
        public ActionResult NewCarPage()
        {
            return View();
        }

        public ActionResult EnterNewCar(CarViewModel tempModel)
        {
            CarModel carModel = new CarModel(tempModel);
            int CarId=1;
            CarDAO.InsertCar(carModel);
            CarPhotoViewModel carPhotoViewModel = new CarPhotoViewModel();
            carPhotoViewModel.Id = CarId;
            return RedirectToAction("UploadPhoto", new { carPhotoViewModel });

        }

        public ActionResult UploadPhoto(CarPhotoViewModel carPhotoViewModel)
        {
            return View(carPhotoViewModel);
        }


        //Must be Edited
        public ActionResult Upload(HttpPostedFileBase file, CarPhotoViewModel carPhotoViewModel)
        {
            if (file != null)
            {
                string pic = System.IO.Path.GetFileName(file.FileName);
                string path = System.IO.Path.Combine(
                                       Server.MapPath("~/img/UserCars"), pic);
                // file is uploaded
                file.SaveAs(path);

                // save the image path path to the database or you can send image
                // directly to database
                // in-case if you want to store byte[] ie. for DB
                using (MemoryStream ms = new MemoryStream())
                {
                    file.InputStream.CopyTo(ms);
                    byte[] array = ms.GetBuffer();
                }

            }
            // after successfully uploading redirect the user
            return RedirectToAction("Index", "Home");
        }

    }
}

FindYourCar/FindYourCar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Find Your Car", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Search", "Index", "Search")</li>
                <li>@Html.ActionLink("New Car", "NewCarPage", "NewCar")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>@Html.ActionLink("Register", "Register", "Account")</li>
                <li>@Html.ActionLink("Log in", "Login", "Account")</li>
            </ul>
        </div>
    </div>
</div>
<div>
    @RenderSection("Slider" , required:false)
</div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>&copy; @DateTime.Now.Year - FindYourCar</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    
    @RenderSection("scripts", required: false)
</body>
</html>